### PR TITLE
Brandon desselle/layout structure

### PR DESCRIPTION
**Pull request by BDesselle**
# Description

In this branch I will be altering the layout structure of my chosen template. 

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [x] Responsiveness
- [x] Cross-browser 

# Milestone Objectives:

- [x] Marketing landing page scaffolded with common layout structure implemented.
- [ ] Marketing site fully responsive to Mobile and Desktop screen widths.
- [ ] Marketing "Login" call to action links user to the Deployed React app login screen.
- [ ] Marketing site replace placeholder copy with description of product.
- [ ] All marketing site pages fully responsive and built out.

# Rubric Objectives:

- [ ] Student's work demonstrates that all MVP features were built and the student went above
and beyond the project.
- [ ] Pair programmed with the Front End Architect.
- [ ] Student layed out the design that matches the example well.  CSS fundamentals such as: box model, flexbox, and positioning were used appropriately.
- [ ] Student's code is clean and organized, proper indentation is apparent, a library or framework was researched and used. 
- [ ] Phone views look professional at 500px and below and Desktop views look professional at 1000px and above. No horizontal scrollbars exist.
- [ ] Tablet views look professional at 800px and above. Responsive units are used for font-sizing.   
- [ ] Objects were created, Array methods were used, code is readable. No errors in the console when opening the web page.
- [ ] Any of the following were used: .map(), .reduce(), .filter(), .sort(), constructors were used to build new objects
- [ ] Event Listeners were used, DOM manipulation occurred
- [ ] A reusable component was built.  The component should be able to take any number of elements and continue to work well.  Example: Accordion with any amount of panels.

# Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

### CODE REVIEW

**Review by Jesse9009 — APPROVED** [review]
index.html changes to customize the template to our app 👍

**Review by brettmadrid — APPROVED** [review]
Approved.  CSS looks good!

**Review by brettmadrid — APPROVED** [review]
Approved

**Review by eddygonzalez9708 — APPROVED** [review]
I will approve these layout changes for the template.

**Comment by eddygonzalez9708** [comment]
I will approve these layout changes for the template.

**Pull request merged**
