### PR TITLE
Editing Placeholders

### PR DESCRIPTION
**Pull request by BDesselle**
# Description

Please include a summary of the change and a link to which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

Fixes # (issue)

# How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Responsiveness
- [ ] Cross-browser 

# Milestone Objectives:

- [ ] Marketing landing page scaffolded with common layout structure implemented.
- [ ] Marketing site fully responsive to Mobile and Desktop screen widths.
- [ ] Marketing "Login" call to action links user to the Deployed React app login screen.
- [ ] Marketing site replace placeholder copy with description of product.
- [ ] All marketing site pages fully responsive and built out.

# Rubric Objectives:

- [ ] Student's work demonstrates that all MVP features were built and the student went above
and beyond the project.
- [ ] Pair programmed with the Front End Architect.
- [ ] Student layed out the design that matches the example well.  CSS fundamentals such as: box model, flexbox, and positioning were used appropriately.
- [ ] Student's code is clean and organized, proper indentation is apparent, a library or framework was researched and used. 
- [ ] Phone views look professional at 500px and below and Desktop views look professional at 1000px and above. No horizontal scrollbars exist.
- [ ] Tablet views look professional at 800px and above. Responsive units are used for font-sizing.   
- [ ] Objects were created, Array methods were used, code is readable. No errors in the console when opening the web page.
- [ ] Any of the following were used: .map(), .reduce(), .filter(), .sort(), constructors were used to build new objects
- [ ] Event Listeners were used, DOM manipulation occurred
- [ ] A reusable component was built.  The component should be able to take any number of elements and continue to work well.  Example: Accordion with any amount of panels.

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

### CODE REVIEW

**Review by Jesse9009 — APPROVED** [review]
Nice job finding all of the places that needed the color updated.

**Review by brettmadrid — APPROVED** [review]
Approved

**Review by brettmadrid — APPROVED** [review]
Looks very good Brandon!

**Review by eddygonzalez9708 — APPROVED** [review]
For your next PR, I cannot wait to see what different color schemes you and Brett will choose for both the marketing site and the front-end application. Also, I noticed when scrolling down on the page the navigation bar takes a while to appear at the top. I think it should appear instantly or be fixed to the top for a better user experience. Let me know what you think about that. Lastly, choose a background color for the navigation bar that does not interfere with the colors for the rest of the content in the marketing site.

**Pull request closed without merging**
